<?php

/**
 * Prepares variables for Views iCal template.
 *
 * Default template: views-view-ical.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical(&$variables) {
  module_load_include('inc', 'views', 'views.theme');

  $view = $variables['view'];
  /** @var \Drupal\views_ical\Plugin\views\style\Ical $ical_style */
  $ical_style = $view->style_plugin;
  $view->getResponse()->headers->set('Content-Type', 'text/calendar; charset=utf-8');
  if ($view->display_handler->getOption('sitename_title')) {
    $config = \Drupal::config('system.site');
    $title = $config->get('name');
    if ($slogan = $config->get('slogan')) {
      $title .= ' - ' . $slogan;
    }
  }
  else {
    $title = $view->getTitle();
  }
  $variables['title'] = $title;

  foreach ($variables['rows'] as $row) {
    $date = $ical_style->getFieldValue($row['#row']->index, $variables['options']['date_field']);
    // TODO: Push date to ical generator.

    $summary = $ical_style->getFieldValue($row['#row']->index, $variables['options']['summary_field']);
    if ($summary) {
      // TODO: Push summary to ical generator.
    }

    $location = $ical_style->getFieldValue($row['#row']->index, $variables['options']['location_field']);
    if ($location) {
      // TODO: Push location to ical generator.
    }
  }

  template_preprocess_views_view_unformatted($variables);
}

/**
 * Prepares variables for Views iCal Fields template.
 *
 * Default template: views-view-ical-fields.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical_fields(&$variables) {
  module_load_include('inc', 'views', 'views.theme');
  template_preprocess_views_view_fields($variables);
}
