<?php

use Eluceo\iCal\Component\Calendar;
use Eluceo\iCal\Component\Event;
use Eluceo\iCal\Component\Timezone;

/**
 * Prepares variables for Views iCal template.
 *
 * Default template: views-view-ical.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical(&$variables) {
  module_load_include('inc', 'views', 'views.theme');

  $view = $variables['view'];
  /** @var \Drupal\views_ical\Plugin\views\style\Ical $ical_style */
  $ical_style = $view->style_plugin;
  $view->getResponse()->headers->set('Content-Type', 'text/calendar; charset=utf-8');
  if ($view->display_handler->getOption('sitename_title')) {
    $config = \Drupal::config('system.site');
    $title = $config->get('name');
    if ($slogan = $config->get('slogan')) {
      $title .= ' - ' . $slogan;
    }
  }
  else {
    $title = $view->getTitle();
  }
  $variables['title'] = $title;

  $calendar = new Calendar('-//Drupal iCal API//EN');
  $user_timezone = \drupal_get_user_timezone();
  $dtz = new \DateTimeZone($user_timezone);

  // Set timezone data to the calendar.
  /** @var string $user_timezone */
  $v_timezone = new Timezone($user_timezone);
  $calendar->setTimezone($v_timezone);

  foreach ($variables['rows'] as $row) {
    $event = new Event();

    // Making sure that the ical calendar has the correct datetime as per user's
    // timezone.
    // An ical calendar downloaded from GMail has been referred as a proof of
    // correctness.
    $date = $ical_style->getFieldValue($row['#row']->index, $variables['options']['date_field']);
    $datetime = new \DateTime($date, new \DateTimeZone('UTC'));
    $datetime->setTimezone($dtz);
    $event->setDtStart($datetime);

    $summary = $ical_style->getFieldValue($row['#row']->index, $variables['options']['summary_field']);
    if ($summary) {
      $event->setSummary($summary);
    }

    $location = $ical_style->getFieldValue($row['#row']->index, $variables['options']['location_field']);
    if ($location) {
      $event->setLocation($location);
    }

    $description = $ical_style->getFieldValue($row['#row']->index, $variables['options']['description_field']);
    if ($description) {
      $event->setDescription(\strip_tags($description));
    }

    $event->setUseTimezone(TRUE);

    $calendar->addComponent($event);
  }

  $variables['ical'] = $calendar->render();

  template_preprocess_views_view_unformatted($variables);
}

/**
 * Prepares variables for Views iCal Fields template.
 *
 * Default template: views-view-ical-fields.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function views_ical_preprocess_views_view_ical_fields(&$variables) {
  module_load_include('inc', 'views', 'views.theme');
  template_preprocess_views_view_fields($variables);
}
